# This is a basic workflow to help you get started with Actions

name: Mansi CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Triggers the workflow based on a schedule
  schedule:
    # Runs at 5:35 AM UTC every day
    - cron: "35 5 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          # Artifact name
          name: Build artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{github.workspace}}

  # This workflow contains a second job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This job will only run after the "build" job is successful
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Download the build artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build artifact
          path: ${{github.workspace}}

      # Runs a single command using the runners shell
      - name: Run tests
        run: echo Running tests...
